name: execute-windows

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - name: Run commands
        shell: pwsh
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
        run: | 
          curl -LO 'https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/win64/chrome-win64.zip'
          unzip chrome*.zip
          ./chrome-win64/chrome.exe --no-sandbox --headless --screenshot=output.png "$env:TARGET_URL"
          env
          set
